# Temporary version for local deployment - (No RBAC available)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: system
  labels:
    app.kubernetes.io/name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
    spec:
      serviceAccount: external-dns
      serviceAccountName: external-dns
      volumes:
        - name: aws-credentials
          emptyDir: {}
        - name: aws-secret
          secret:
            secretName: external-dns
      initContainers:
        - name: write-aws-creds
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /.aws
              echo "[default]" > /.aws/credentials
              echo "aws_access_key_id=$(cat /secret/aws_access_key)" >> /.aws/credentials
              echo "aws_secret_access_key=$(cat /secret/aws_secret_key)" >> /.aws/credentials
          volumeMounts:
            - name: aws-credentials
              mountPath: /.aws
            - name: aws-secret
              mountPath: /secret
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.18.0
          args:
            - --source=service
            - --source=ingress
            - --provider=aws
            - --aws-zone-type=public
            - --registry=txt
            - --txt-owner-id=k8s-playground
          env:
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /.aws/credentials
          volumeMounts:
            - name: aws-credentials
              mountPath: /.aws
              readOnly: true