apiVersion: v1
kind: Secret
metadata:
    name: kustomize-controller
    namespace: flux-system
type: Opaque
data:
    aws_access_key: ENC[AES256_GCM,data:YjCxqxXPpZcLOz+jNiw+5Y2+SVCFY/4Pyp9vdA==,iv:++xJE9ZQeSyQAa8GfAz8LMhS4NGmHw+c+Avp2xI052w=,tag:6nxWAEDybVJ9au0+FV4zkg==,type:str]
    aws_secret_key: ENC[AES256_GCM,data:6yd3KKM6yj65Ug3qtiGp5Y0hSzuV7vrOE8qe7F0rzTdka5N4P+nQbXEVBA2V1V5dy4GRliOAcDs=,iv:b8yuiPAhRyXvBQ7ZsSHFxcKj+0JA5572CrKOc46bhJQ=,tag:LOotBIUcdKd5+o14CCrjXw==,type:str]
sops:
    kms:
        - arn: "${KMS_KEY_ARN}"
          created_at: "2025-08-24T14:25:55Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgHAi3mPi/SA3Ml3I/nclfaxAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0ZgkcmTelXxqK0hAAgEQgDsjHsmp3KMSpLOCXAYmkNpgoWmQ1mViAth3RcPVkIXu58O1e2ymZmSSpqGjmvfTY8ugsw3504OiMweC3g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-24T14:25:55Z"
    mac: ENC[AES256_GCM,data:DJ9rnVSMrvY5a35vtS0+0ppD4O1VfecFa59nrAn8g6c1Kb1hXovv/JB2L/Ipjkxq1bPdSUkDfbCuRZcZWSaE3qKDsmTst7Wy5jgUJuVLng48JC8/uQ0iaqvG6gsq7jE1uIoHECePHHOnoRFsKet0BNWB+fTjDfWeEPhviI7Q27I=,iv:KUMzpogrlgkLJSVUNdTRDEBHCB7kNQH9Rn+iyBH41ZY=,tag:oPT+zvurOoT0FG2chQ2Pdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
