replicaCount: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: my-api.example.com
      paths:
        - path: /
          pathType: Prefix

resources: {}
