helm_releases:
  - name: traefik
    namespace: traefik
    repository: https://helm.traefik.io/traefik
    chart: traefik
    version: v35.4.0
    wait: true

  - name: prometheus
    disabled: true
    namespace: monitoring
    repository: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    version: "v73.2.0"
    wait: true

  - name: cert-manager
    namespace: system
    repository: https://charts.jetstack.io
    chart: cert-manager
    version: v1.18.0
    wait: true
    set:
      - name: crds.enabled
        value: "true"

  - name: flux2
    disabled: false
    namespace: flux-system
    repository: https://fluxcd-community.github.io/helm-charts
    chart: flux2
    version: 2.12.4
    wait: true

  - name: flux-system
    disabled: false
    namespace: flux-system
    repository: https://fluxcd-community.github.io/helm-charts
    chart: flux2-sync
    version: 1.8.2
    wait: true
    set:
      - name: gitRepository.spec.url
        value: "https://github.com/gerardvm/k8s-playground.git"
      - name: gitRepository.spec.ref.branch
        value: "main"
      - name: gitRepository.spec.interval
        value: "1m"

  - name: my-rest-api
    disabled: true
    namespace: staging-my-rest-api
    repository: ../../k8s/charts
    chart: my-rest-api
    version: 0.1.0
    wait: true
    variables:
      replicaCount: 1
      subdomain: staging.
      domain: k8s-playground.gerardvm.tech
      message: "Hello from my-api staging environment!"

  - name: my-rest-api
    disabled: false
    namespace: prod-my-rest-api
    repository: ../../k8s/charts
    chart: my-rest-api
    version: 0.1.0
    wait: true
    variables:
      replicaCount: 2
      subdomain: ""
      domain: k8s-playground.gerardvm.tech
      message: "Hello from my-api production environment!"
