helm_releases:
  - name: traefik
    namespace: traefik
    repository: https://helm.traefik.io/traefik
    chart: traefik
    version: v35.4.0
    wait: true

  - name: prometheus
    disabled: true
    namespace: monitoring
    repository: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    version: "v73.2.0"
    wait: true

  - name: my-rest-api
    disabled: true
    namespace: staging-my-rest-api
    repository: ../../k8s/charts
    chart: my-rest-api
    version: 0.1.0
    wait: true
    variables:
      replicaCount: 1
      image: nginx
      subdomain: staging.

  - name: my-rest-api
    disabled: false
    namespace: prod-my-rest-api
    repository: ../../k8s/charts
    chart: my-rest-api
    version: 0.1.0
    wait: true
    variables:
      replicaCount: 2
      image: nginx
      subdomain: ""
