apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
spec:
  interval: 5m
  type: oci
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: "1.19.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
  values:
    provider: aws
    txtOwnerId: gerardvm
    txtPrefix: k8s-playground
    policy: sync
    # env:
    #   - name: AWS_DEFAULT_REGION
    #     value: us-east-1
    #   - name: AWS_ACCESS_KEY_ID
    #     valueFrom:
    #       secretKeyRef:
    #         name: aws-credentials
    #         key: AWS_ACCESS_KEY_ID
    #   - name: AWS_SECRET_ACCESS_KEY  
    #     valueFrom:
    #       secretKeyRef:
    #         name: aws-credentials
    #         key: AWS_SECRET_ACCESS_KEY
    #   - name: AWS_SESSION_TOKEN
    #     valueFrom:
    #       secretKeyRef:
    #         name: aws-credentials  
    #         key: AWS_SESSION_TOKEN
