helm_releases:
  - name: my-rest-api
    disabled: true
    namespace: staging-my-rest-api
    repository: ../../k8s/charts
    chart: my-rest-api
    version: 0.1.0
    wait: true
    variables:
      replicaCount: 1
      image: nginx
      subdomain: staging.
  - name: my-rest-api
    disabled: false
    namespace: prod-my-rest-api
    repository: ../../k8s/charts
    chart: my-rest-api
    version: 0.1.0
    wait: true
    variables:
      replicaCount: 2
      image: nginx
      subdomain: ""
