namespaces:
  - traefik
  - monitoring

helm_releases:
  - name: traefik
    namespace: traefik
    repository: https://helm.traefik.io/traefik
    chart: traefik
    version: v35.4.0
    wait: true
  - name: prometheus
    disabled: true
    namespace: monitoring
    repository: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    version: "v73.2.0"
    wait: true