replicaCount: ${replicaCount}

env:
  listenHost: 0.0.0.0
  listenPort: 5678

image:
  repository: hashicorp/http-echo
  tag: latest
  pullPolicy: IfNotPresent
  containerPort: 5678

service:
  type: ClusterIP
  port: 5678

ingress:
  enabled: true
  className: traefik
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ${subdomain}${domain}
      paths:
        - path: /
          pathType: Prefix
