name: Start and stop test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      KMS_KEY_ARN: ${{ vars.KMS_KEY_ARN }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      AWS_ROLE: ${{ vars.AWS_ROLE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE }}
          role-session-name: k8s-playground
          aws-region: ${{ env.AWS_REGION }}

      - name: Enable all disabled components in config
        run: |
          sed -i 's/disabled: true/disabled: false/g' terraform/k8s/helm_releases.yaml
          sed -i 's/disabled: true/disabled: false/g' terraform/k8s/helm_releases.yaml

      - name: Inject KMS key ARN into kubernetes secrets
        run: |
          for file in k8s/terraform/secrets/*.yaml; do
            sed -i "s|\${KMS_KEY_ARN}|${{ env.KMS_KEY_ARN }}|g" "$file"
          done

      - name: Start kind cluster
        run: make start TERRAFORM_OPT="--auto-approve"

      - name: Run smoke tests
        run: |
          set -e  # exit immediately if a command fails
          declare -A tests=(
              ["Prometheus"]="http://localhost:30001"
              ["k8s-playground.gerardvm.tech"]="http://k8s-playground.gerardvm.tech:30000"
              ["staging.k8s-playground.gerardvm.tech"]="http://staging.k8s-playground.gerardvm.tech:30000"
          )
          for service in "${!tests[@]}"; do
              echo "Testing $service..."
              if curl -sSf "${tests[$service]}"; then
                  echo "$service is up ✅"
              else
                  echo "$service test failed ❌"
                  exit 1
              fi
          done

      - name: Stop kind cluster
        run: make stop TERRAFORM_OPT="--auto-approve"
